# Sudo used for custom apt setup
sudo: true

# Add new environments to the build here:
env:
  - GHCVER=8.0.2  CABALVER=2.4
  - GHCVER=8.2.2  CABALVER=2.4
  - GHCVER=8.4.4  CABALVER=2.4
  - GHCVER=8.6.4  CABALVER=2.4
  - GHCVER=head   CABALVER=head

cache:
  directories:
    - "home/travis/.cabal/"

# Allow for develop branch to break
matrix:
  allow_failures:
    - env: GHCVER=head   CABALVER=head

# Manually install ghc and cabal
before_install:
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
  - export PATH=$HOME/.cabal/bin:$PATH
  - travis_retry cabal v2-update

install:
  - echo $PATH
  - cabal --version
  - ghc --version
  - cabal v2-configure --enable-tests

script:
  - cabal v2-build
  - cabal v2-test
